"""Shared chance gates for same-sex romance systems."""

import random

# Keep same-sex and mixed sterilization romance possible, but extremely rare
# when it is generated by code.
RARE_ROMANCE_CHANCE = 25000
# Backwards-compatible name for existing tests and imports.
SAME_SEX_ROMANCE_CHANCE = RARE_ROMANCE_CHANCE
STERILIZED_INTACT_ROMANCE_CHANCE = RARE_ROMANCE_CHANCE


def cats_are_same_sex(cat_from, cat_to) -> bool:
    """Return True when two cats have the same sex/gender value."""
    return bool(cat_from and cat_to and cat_from.gender == cat_to.gender)


def cat_is_sterilized(cat) -> bool:
    """Return True when a cat has a sterilization permanent condition."""
    return bool(
        cat
        and any(
            condition in getattr(cat, "permanent_condition", {})
            for condition in ("neutered", "spayed")
        )
    )


def cats_are_mixed_sterilization(cat_from, cat_to) -> bool:
    """Return True when only one cat in a pair is spayed/neutered."""
    return cat_is_sterilized(cat_from) != cat_is_sterilized(cat_to)


def passes_rare_romance_chance(cat_from, cat_to) -> bool:
    """Return whether generated romance is allowed for rare-romance pairs.

    Same-sex pairs and mixed spayed/neutered-intact pairs have a 1-in-25,000
    chance. Other pairings always pass. This shared gate keeps romantic
    interactions, romance gains, potential-mate filtering, confessions, and
    automatic mate creation in sync.
    """
    if not cats_are_same_sex(cat_from, cat_to) and not cats_are_mixed_sterilization(
        cat_from, cat_to
    ):
        return True

    return random.randint(1, RARE_ROMANCE_CHANCE) == 1


def passes_same_sex_romance_chance(cat_from, cat_to) -> bool:
    """Return whether a generated same-sex romance attempt is allowed."""
    return passes_rare_romance_chance(cat_from, cat_to)
