"""Shared chance gates for same-sex romance systems."""

import random

# Keep same-sex romance possible, but extremely rare when it is generated by code.
SAME_SEX_ROMANCE_CHANCE = 25000


def cats_are_same_sex(cat_from, cat_to) -> bool:
    """Return True when two cats have the same sex/gender value."""
    return bool(cat_from and cat_to and cat_from.gender == cat_to.gender)


def passes_same_sex_romance_chance(cat_from, cat_to) -> bool:
    """Return whether a generated same-sex romance attempt is allowed.

    Opposite-sex pairs always pass. Same-sex pairs have a 1-in-25,000 chance.
    This helper is intentionally shared by romantic interactions, romance gains,
    potential-mate filtering, confessions, and automatic mate creation so those
    systems do not drift out of balance independently.
    """
    if not cats_are_same_sex(cat_from, cat_to):
        return True

    return random.randint(1, SAME_SEX_ROMANCE_CHANCE) == 1
